name: catalog_cart_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  get: ^4.6.6
  shared_preferences: ^2.2.3
  dio: ^5.7.0
  sqflite: ^2.3.3+1
  connectivity_plus: ^6.1.0
  sembast: ^3.7.1
  path_provider: ^2.1.4
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  

 
